[package]
name = "jdpay"
version = "0.0.0"
edition = "2021"
description = "jdpay-sdk-rs"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
